/*
 * Build Timestamp Timeline into a directly installable plugin folder.
 *
 *   node esbuild.config.mjs              → watch, dev sourcemap
 *   node esbuild.config.mjs production   → minified, no sourcemap, copies assets
 */
import esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the repository in the package.json "repository" field
*/
`;

const prod = process.argv[2] === 'production';

const common = {
  banner: { js: banner },
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
};

/** The three files Obsidian needs. Copied verbatim from src/. */
const ARTIFACTS = ['manifest.json', 'styles.css'];

function copyAssets() {
  for (const asset of ARTIFACTS) {
    const src = path.join('src', asset);
    if (fs.existsSync(src)) fs.copyFileSync(src, asset);
  }
}

const ctx = await esbuild.context({
  ...common,
  entryPoints: ['src/main.ts'],
  outfile: 'main.js',
});

if (prod) {
  await ctx.rebuild();
  copyAssets();
  await ctx.dispose();
  process.exit(0);
} else {
  copyAssets();
  await ctx.watch();
}
